import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  { path: '/', redirect: '/install' },
  { path: '/install', component: () => import('./pages/InstallPage.vue'), meta: { title: '📦 Install', description: 'Install vue-ui-select via npm and configure it as a Vue 3 plugin or individual import, with theme setup and TypeScript support.' } },
  { path: '/getting-started', component: () => import('./pages/GettingStartedPage.vue'), meta: { title: '🚀 Getting Started', description: 'Step-by-step guide to using vue-ui-select — from basic usage to multiple selection, tagging, grouping, and custom templates.' } },
  { path: '/basic', component: () => import('./pages/BasicPage.vue'), meta: { title: 'Basic', description: 'Basic single-select dropdown demo with vue-ui-select using a simple array of strings.' } },
  { path: '/append-to-body', component: () => import('./pages/AppendToBodyPage.vue'), meta: { title: 'Append To Body', description: 'Teleport the dropdown to the document body to avoid overflow clipping issues.' } },
  { path: '/bind-single-property', component: () => import('./pages/BindSinglePropertyPage.vue'), meta: { title: 'Bind To Single Property', description: 'Bind the selected value to a single object property instead of the full object.' } },
  { path: '/bind-single-property-async', component: () => import('./pages/BindSinglePropertyAsyncPage.vue'), meta: { title: 'Bind To Single Property Async', description: 'Async data loading with single-property binding using vue-ui-select.' } },
  { path: '/disable-search', component: () => import('./pages/DisableSearchPage.vue'), meta: { title: 'Disable Search', description: 'Disable the built-in search input to create a simple dropdown without filtering.' } },
  { path: '/dropdown-position', component: () => import('./pages/DropdownPositionPage.vue'), meta: { title: 'Dropdown Position', description: 'Control whether the dropdown opens above or below the select component.' } },
  { path: '/event-on-selection', component: () => import('./pages/EventOnSelectionPage.vue'), meta: { title: 'Event On Selection', description: 'Listen for selection change events emitted by vue-ui-select.' } },
  { path: '/focus', component: () => import('./pages/FocusPage.vue'), meta: { title: 'Focus', description: 'Programmatically focus the select component and respond to focus/blur events.' } },
  { path: '/group-by', component: () => import('./pages/GroupByPage.vue'), meta: { title: 'Group By', description: 'Group dropdown options by a property using the group-by directive.' } },
  { path: '/group-filter', component: () => import('./pages/GroupFilterPage.vue'), meta: { title: 'Group Filter', description: 'Filter and reorder option groups with a custom group-filter function.' } },
  { path: '/multiple-selection', component: () => import('./pages/MultipleSelectionPage.vue'), meta: { title: 'Multiple Selection', description: 'Enable multi-select with tag-style chips for choosing multiple values.' } },
  { path: '/object-as-source', component: () => import('./pages/ObjectAsSourcePage.vue'), meta: { title: 'Object As Source', description: 'Use an array of objects as the data source with custom display properties.' } },
  { path: '/tagging', component: () => import('./pages/TaggingPage.vue'), meta: { title: 'Tagging', description: 'Allow users to create new tags on the fly with the tagging feature.' } },
  { path: '/bootstrap-theme', component: () => import('./pages/BootstrapThemePage.vue'), meta: { title: 'Bootstrap Theme', description: 'vue-ui-select styled with the Bootstrap theme for Bootstrap-based projects.' } },
  { path: '/select2-theme', component: () => import('./pages/Select2ThemePage.vue'), meta: { title: 'Select2 Theme', description: 'vue-ui-select styled with the Select2 theme for a familiar jQuery Select2 look.' } },
  { path: '/selectize-theme', component: () => import('./pages/SelectizeThemePage.vue'), meta: { title: 'Selectize Theme', description: 'vue-ui-select styled with the Selectize theme for a clean, modern look.' } },
  { path: '/tailwind', component: () => import('./pages/TailwindPage.vue'), meta: { title: 'Tailwind', description: 'vue-ui-select with the Tailwind CSS theme — utility-first styling out of the box.' } },
  { path: '/tailwind-multiple', component: () => import('./pages/TailwindMultiplePage.vue'), meta: { title: 'Tailwind + Multiple', description: 'Tailwind-themed multi-select with tag chips and remove buttons.' } },
  { path: '/tailwind-grouped', component: () => import('./pages/TailwindGroupedPage.vue'), meta: { title: 'Tailwind + Grouped', description: 'Tailwind-themed select with grouped options using group-by.' } },
  { path: '/tailwind-tagging', component: () => import('./pages/TailwindTaggingPage.vue'), meta: { title: 'Tailwind + Tagging', description: 'Tailwind-themed tagging mode — create custom tags inline.' } },
  { path: '/tailwind-teleport', component: () => import('./pages/TailwindTeleportPage.vue'), meta: { title: 'Tailwind + Teleport', description: 'Tailwind-themed select with the dropdown teleported to the document body.' } },
  { path: '/tailwind-states', component: () => import('./pages/TailwindStatesPage.vue'), meta: { title: 'Tailwind + States', description: 'Tailwind-themed select demonstrating disabled, loading, and placeholder states.' } },
  { path: '/tailwind-dark-mode', component: () => import('./pages/TailwindDarkModePage.vue'), meta: { title: 'Tailwind + Dark Mode', description: 'Tailwind-themed select with dark mode support using the dark: variant.' } },
  { path: '/performance', component: () => import('./pages/PerformancePage.vue'), meta: { title: '⚡ Performance', description: 'Stress-test vue-ui-select with 1K to 20K options — measure render and search performance.' } },
]
