import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  { path: '/', redirect: '/install' },
  { path: '/install', component: () => import('./pages/InstallPage.vue'), meta: { title: '📦 Install' } },
  { path: '/getting-started', component: () => import('./pages/GettingStartedPage.vue'), meta: { title: '🚀 Getting Started' } },
  { path: '/basic', component: () => import('./pages/BasicPage.vue'), meta: { title: 'Basic' } },
  { path: '/append-to-body', component: () => import('./pages/AppendToBodyPage.vue'), meta: { title: 'Append To Body' } },
  { path: '/bind-single-property', component: () => import('./pages/BindSinglePropertyPage.vue'), meta: { title: 'Bind To Single Property' } },
  { path: '/bind-single-property-async', component: () => import('./pages/BindSinglePropertyAsyncPage.vue'), meta: { title: 'Bind To Single Property Async' } },
  { path: '/disable-search', component: () => import('./pages/DisableSearchPage.vue'), meta: { title: 'Disable Search' } },
  { path: '/dropdown-position', component: () => import('./pages/DropdownPositionPage.vue'), meta: { title: 'Dropdown Position' } },
  { path: '/event-on-selection', component: () => import('./pages/EventOnSelectionPage.vue'), meta: { title: 'Event On Selection' } },
  { path: '/focus', component: () => import('./pages/FocusPage.vue'), meta: { title: 'Focus' } },
  { path: '/group-by', component: () => import('./pages/GroupByPage.vue'), meta: { title: 'Group By' } },
  { path: '/group-filter', component: () => import('./pages/GroupFilterPage.vue'), meta: { title: 'Group Filter' } },
  { path: '/multiple-selection', component: () => import('./pages/MultipleSelectionPage.vue'), meta: { title: 'Multiple Selection' } },
  { path: '/object-as-source', component: () => import('./pages/ObjectAsSourcePage.vue'), meta: { title: 'Object As Source' } },
  { path: '/tagging', component: () => import('./pages/TaggingPage.vue'), meta: { title: 'Tagging' } },
  { path: '/bootstrap-theme', component: () => import('./pages/BootstrapThemePage.vue'), meta: { title: 'Bootstrap Theme' } },
  { path: '/select2-theme', component: () => import('./pages/Select2ThemePage.vue'), meta: { title: 'Select2 Theme' } },
  { path: '/selectize-theme', component: () => import('./pages/SelectizeThemePage.vue'), meta: { title: 'Selectize Theme' } },
  { path: '/tailwind', component: () => import('./pages/TailwindPage.vue'), meta: { title: 'Tailwind' } },
  { path: '/tailwind-multiple', component: () => import('./pages/TailwindMultiplePage.vue'), meta: { title: 'Tailwind + Multiple' } },
  { path: '/tailwind-grouped', component: () => import('./pages/TailwindGroupedPage.vue'), meta: { title: 'Tailwind + Grouped' } },
  { path: '/tailwind-tagging', component: () => import('./pages/TailwindTaggingPage.vue'), meta: { title: 'Tailwind + Tagging' } },
  { path: '/tailwind-teleport', component: () => import('./pages/TailwindTeleportPage.vue'), meta: { title: 'Tailwind + Teleport' } },
  { path: '/tailwind-states', component: () => import('./pages/TailwindStatesPage.vue'), meta: { title: 'Tailwind + States' } },
  { path: '/tailwind-dark-mode', component: () => import('./pages/TailwindDarkModePage.vue'), meta: { title: 'Tailwind + Dark Mode' } },
  { path: '/performance', component: () => import('./pages/PerformancePage.vue'), meta: { title: '⚡ Performance' } },
]
